---
- hosts: eos_demo_group
  gather_facts: no
  connection: local

  tasks:
      - name: load an acl into the device
        eos_config:
          lines:
            - 10 permit ip 1.1.1.1/32 any log
            - 20 permit ip 2.2.2.2/32 any log
            - 30 permit ip 3.3.3.3/32 any log
            - 40 permit ip 4.4.4.4/32 any log
          parents: ip access-list test
          before: no ip access-list test
          replace: block
          provider: '{{ provider }}'

#      - name: Arista EOS Base Configuration
#        eos_config:
#          command='ntp server 192.5.41.41'
#          provider: '{{ provider }}'
#      - name: idempotent operation for removing a SVI
#        eos_config:
#          lines:
#            command='no interface Vlan100'
#            regexp='interface Vlan100'
#            state=absent
#            provider: '{{ provider1 }}'
