---
- name: Arista Example
  hosts: arista

  tasks:
    - name: EOS get the facts!
      eos_banner:
        banner: login
        text: |
          This is a secure network, all activity is monitored.
          If you do not have permission to connect then don't
          If you do I will beat your ass, no really I will.
        state: present
        provider: "{{ provider_eapi }}"
