---
- name: Arista SSH settings
  hosts: arista

  tasks:

    - name: configure Arista SSH settings
      eos_config:
        lines:
          - "idle-timeout 60"
          - "no shutdown"
          - "login timeout 90"
        parents: management ssh
        defaults: yes
        provider: "{{ provider_eapi }}"
