---
- name: Arista Example
  hosts: arista

  tasks:
    - name: Simple way to add 1 vlan to Arista switches.
      eos_vlan:
        vlan_id: 4000
        name: 4000-Wifi
        state: present
        provider: "{{ provider_cli }}"
