---
- name: Arista Example
  hosts: arista

  tasks:
    - name: EOS setup buffer logging
      eos_logging:
        dest: buffered
        size: 5000
        state: present
        provider: "{{ provider_eapi }}"

    - name: configure host logging
      eos_logging:
        dest: host
        name: 172.16.0.1
        state: present 
        provider: "{{ provider_eapi }}"
