---
- name: Arista Example
  hosts: arista

  tasks:
    - name: use EOS config command
      eos_config:
        lines:
          - 10 permit ip 1.1.1.1/32 any log
          - 20 permit ip 2.2.2.2/32 any log
          - 30 permit ip 3.3.3.3/32 any log
          - 40 permit ip 4.4.4.4/32 any log
        parents: ip access-list test
        before: no ip access-list test
        replace: block
        provider: "{{ provider_cli }}"
