---
- name: Arista Example
  hosts: arista

  tasks:
    - name: configure the login banner
      eos_banner:
        banner: login
        text: |
          this is my login banner
          that contains a multiline
          string
        state: present
